// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConnectionEventsSet(arg1) {
  return window['go']['events']['ConnectionEvents']['GetConnectionEventsSet'](arg1);
}
