// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {events} from '../models';

export function GetConnectionEventsSet(arg1:number):Promise<events.ConnectionEventsSet>;
