// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mqtt$0 from "../mqtt/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as update$0 from "../update/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddSubscription(connectionId: number): $CancellablePromise<models$0.Subscription | null> {
    return $Call.ByID(1707702138, connectionId).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Exposed to frontend to call as necessary
 */
export function CheckForUpdates(): $CancellablePromise<update$0.UpdateResponse | null> {
    return $Call.ByID(2570002251).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ChooseCertFile(title: string): $CancellablePromise<string> {
    return $Call.ByID(2632460757, title);
}

export function ChooseDirectory(title: string): $CancellablePromise<string> {
    return $Call.ByID(1399537760, title);
}

export function ClearConnectionHistory(connId: number): $CancellablePromise<void> {
    return $Call.ByID(4129774215, connId);
}

export function ConnectMqtt(connId: number): $CancellablePromise<void> {
    return $Call.ByID(1025617036, connId);
}

export function CreateCollection(params: $models.CreateCollectionParams): $CancellablePromise<models$0.Collection> {
    return $Call.ByID(2462867700, params).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * DeleteCollection removes a collection and all messages in it.
 */
export function DeleteCollection(id: number): $CancellablePromise<void> {
    return $Call.ByID(3185313063, id);
}

export function DeleteCollectionMessage(id: number): $CancellablePromise<void> {
    return $Call.ByID(3507400934, id);
}

export function DeleteConnection(id: number): $CancellablePromise<void> {
    return $Call.ByID(4008925183, id);
}

export function DeleteFilterHistoryEntry(connectionId: number, text: string): $CancellablePromise<void> {
    return $Call.ByID(449713245, connectionId, text);
}

export function DeletePublishHistoryEntry(id: number): $CancellablePromise<void> {
    return $Call.ByID(626243294, id);
}

export function DeleteRetainedMessage(connId: number, topic: string): $CancellablePromise<void> {
    return $Call.ByID(1837950630, connId, topic);
}

export function DeleteSubscription(connId: number, id: number): $CancellablePromise<void> {
    return $Call.ByID(1291658, connId, id);
}

export function DisconnectMqtt(connId: number): $CancellablePromise<void> {
    return $Call.ByID(2595921592, connId);
}

export function DuplicateCollectionMessage(id: number): $CancellablePromise<models$0.CollectionMessage> {
    return $Call.ByID(2896789728, id).then(($result: any) => {
        return $$createType5($result);
    });
}

export function ExportAllMessages(connId: number): $CancellablePromise<string> {
    return $Call.ByID(2360991441, connId);
}

export function ExportTopicMessages(connId: number, topic: string): $CancellablePromise<string> {
    return $Call.ByID(2895564909, connId, topic);
}

export function GetAllConnections(): $CancellablePromise<$models.Connections> {
    return $Call.ByID(3922339528).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetAllSubscriptionsByConnectionId(): $CancellablePromise<{ [_ in `${number}`]?: models$0.Subscription[] }> {
    return $Call.ByID(3141731323).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetCollectionsForConnection returns global collections (connection_id IS NULL)
 * plus collections scoped to the given connection, messages preloaded.
 */
export function GetCollectionsForConnection(connectionID: number): $CancellablePromise<models$0.Collection[]> {
    return $Call.ByID(2553763368, connectionID).then(($result: any) => {
        return $$createType9($result);
    });
}

export function GetEnvInfo(): $CancellablePromise<$models.EnvInfo> {
    return $Call.ByID(3369643427).then(($result: any) => {
        return $$createType10($result);
    });
}

export function GetFilterHistoriesForConnection(connectionID: number): $CancellablePromise<models$0.FilterHistory[]> {
    return $Call.ByID(2941945813, connectionID).then(($result: any) => {
        return $$createType12($result);
    });
}

export function GetMatchingSubscriptionForTopic(connId: number, topic: string): $CancellablePromise<models$0.Subscription | null> {
    return $Call.ByID(2749766752, connId, topic).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetMessageHistory(connId: number, topic: string): $CancellablePromise<mqtt$0.MqttMessage[]> {
    return $Call.ByID(3700437937, connId, topic).then(($result: any) => {
        return $$createType14($result);
    });
}

export function GetMqttStats(): $CancellablePromise<$models.MqttStats> {
    return $Call.ByID(2888945465).then(($result: any) => {
        return $$createType15($result);
    });
}

export function GetPanelSizes(): $CancellablePromise<models$0.PanelSize[]> {
    return $Call.ByID(3836927596).then(($result: any) => {
        return $$createType17($result);
    });
}

export function GetPublishHistoriesForConnection(connectionID: number): $CancellablePromise<models$0.PublishHistory[]> {
    return $Call.ByID(3102818020, connectionID).then(($result: any) => {
        return $$createType19($result);
    });
}

export function GetSortStates(): $CancellablePromise<models$0.SortState[]> {
    return $Call.ByID(2748919454).then(($result: any) => {
        return $$createType21($result);
    });
}

export function LoadOpenTabs(): $CancellablePromise<models$0.Tab[]> {
    return $Call.ByID(2526018972).then(($result: any) => {
        return $$createType23($result);
    });
}

export function MoveCollectionMessage(id: number, targetCollectionID: number): $CancellablePromise<models$0.CollectionMessage> {
    return $Call.ByID(184359020, id, targetCollectionID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function NewConnection(): $CancellablePromise<$models.Connection | null> {
    return $Call.ByID(3098702478).then(($result: any) => {
        return $$createType25($result);
    });
}

export function PublishMqtt(connId: number, message: $models.PublishParams): $CancellablePromise<void> {
    return $Call.ByID(3575117605, connId, message);
}

export function RenameCollection(id: number, name: string): $CancellablePromise<models$0.Collection> {
    return $Call.ByID(1111441190, id, name).then(($result: any) => {
        return $$createType4($result);
    });
}

export function RenameCollectionMessage(id: number, name: string): $CancellablePromise<models$0.CollectionMessage> {
    return $Call.ByID(379007077, id, name).then(($result: any) => {
        return $$createType5($result);
    });
}

export function SaveCollectionMessage(params: $models.SaveCollectionMessageParams): $CancellablePromise<models$0.CollectionMessage> {
    return $Call.ByID(1468270044, params).then(($result: any) => {
        return $$createType5($result);
    });
}

export function SaveFilterHistoryEntry(connectionId: number, text: string): $CancellablePromise<models$0.FilterHistory> {
    return $Call.ByID(481334387, connectionId, text).then(($result: any) => {
        return $$createType11($result);
    });
}

export function SavePublishHistoryEntry(params: $models.SavePublishHistoryEntryParams): $CancellablePromise<models$0.PublishHistory> {
    return $Call.ByID(3794014424, params).then(($result: any) => {
        return $$createType18($result);
    });
}

export function StartUpdate(): $CancellablePromise<void> {
    return $Call.ByID(1435025345);
}

export function Startup(options: $models.StartupOptions | null): $CancellablePromise<void> {
    return $Call.ByID(1674476365, options);
}

export function UpdateConnection(conn: models$0.Connection | null): $CancellablePromise<void> {
    return $Call.ByID(2567523649, conn);
}

export function UpdateOpenConnectionTabs(connIds: number[]): $CancellablePromise<void> {
    return $Call.ByID(1501318837, connIds);
}

export function UpdatePanelSize(panelId: string, size: number, isOpen: boolean): $CancellablePromise<void> {
    return $Call.ByID(1524249556, panelId, size, isOpen);
}

export function UpdateSortState(sortId: string, sortCriteria: string, sortDirection: string): $CancellablePromise<void> {
    return $Call.ByID(2265023050, sortId, sortCriteria, sortDirection);
}

export function UpdateSubscription(connId: number, sub: models$0.Subscription): $CancellablePromise<models$0.Subscription | null> {
    return $Call.ByID(1582032348, connId, sub).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = models$0.Subscription.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = update$0.UpdateResponse.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = models$0.Collection.createFrom;
const $$createType5 = models$0.CollectionMessage.createFrom;
const $$createType6 = $models.Connections.createFrom;
const $$createType7 = $Create.Array($$createType0);
const $$createType8 = $Create.Map($Create.Any, $$createType7);
const $$createType9 = $Create.Array($$createType4);
const $$createType10 = $models.EnvInfo.createFrom;
const $$createType11 = models$0.FilterHistory.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = mqtt$0.MqttMessage.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = $models.MqttStats.createFrom;
const $$createType16 = models$0.PanelSize.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = models$0.PublishHistory.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = models$0.SortState.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = models$0.Tab.createFrom;
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = $models.Connection.createFrom;
const $$createType25 = $Create.Nullable($$createType24);
