// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mqtt$0 from "../mqtt/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as update$0 from "../update/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AcknowledgeChangelog records that the user has seen the "What's new" dialog
 * for the given app version, so it isn't shown again until the next update.
 */
export function AcknowledgeChangelog(version: string): Promise<models$0.AppSettings> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3277405218, version) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType0($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * AcknowledgeStarPrompt records that the user has seen the "star us on GitHub"
 * prompt, so it never shows again (whether they starred or dismissed it).
 */
export function AcknowledgeStarPrompt(): Promise<models$0.AppSettings> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2492238430) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType0($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function AddSubscription(connectionId: number): Promise<models$0.Subscription | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1707702138, connectionId) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType2($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * Exposed to frontend to call as necessary
 */
export function CheckForUpdates(): Promise<update$0.UpdateResponse | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2570002251) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType4($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function ChooseCertFile(title: string): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2632460757, title) as any;
    return $resultPromise;
}

export function ChooseDirectory(title: string): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1399537760, title) as any;
    return $resultPromise;
}

export function ClearConnectionHistory(connId: number): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4129774215, connId) as any;
    return $resultPromise;
}

/**
 * ClearReceivedMessages deletes all durable history (optionally for one
 * connection) and compacts the file.
 */
export function ClearReceivedMessages(connectionID: number): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3528502082, connectionID) as any;
    return $resultPromise;
}

export function ConnectMqtt(connId: number): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1025617036, connId) as any;
    return $resultPromise;
}

export function CreateCollection(params: $models.CreateCollectionParams): Promise<models$0.Collection> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2462867700, params) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType5($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * DeleteCollection removes a collection and all messages in it.
 */
export function DeleteCollection(id: number): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3185313063, id) as any;
    return $resultPromise;
}

export function DeleteCollectionMessage(id: number): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3507400934, id) as any;
    return $resultPromise;
}

export function DeleteConnection(id: number): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4008925183, id) as any;
    return $resultPromise;
}

export function DeleteFilterHistoryEntry(connectionId: number, text: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(449713245, connectionId, text) as any;
    return $resultPromise;
}

export function DeletePublishHistoryEntry(id: number): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(626243294, id) as any;
    return $resultPromise;
}

export function DeleteRetainedMessage(connId: number, topic: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1837950630, connId, topic) as any;
    return $resultPromise;
}

export function DeleteSubscription(connId: number, id: number): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1291658, connId, id) as any;
    return $resultPromise;
}

export function DisconnectMqtt(connId: number): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2595921592, connId) as any;
    return $resultPromise;
}

export function DuplicateCollectionMessage(id: number): Promise<models$0.CollectionMessage> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2896789728, id) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType6($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function ExportAllMessages(connId: number): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2360991441, connId) as any;
    return $resultPromise;
}

export function ExportTopicMessages(connId: number, topic: string): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2895564909, connId, topic) as any;
    return $resultPromise;
}

export function GetAllConnections(): Promise<$models.Connections> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3922339528) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType7($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function GetAllSubscriptionsByConnectionId(): Promise<{ [_: `${number}`]: models$0.Subscription[] }> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3141731323) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType9($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetAppSettings returns the singleton settings row (seeded by migration).
 */
export function GetAppSettings(): Promise<models$0.AppSettings> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3769940222) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType0($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetCollectionsForConnection returns global collections (connection_id IS NULL)
 * plus collections scoped to the given connection, messages preloaded.
 */
export function GetCollectionsForConnection(connectionID: number): Promise<models$0.Collection[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2553763368, connectionID) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType10($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetDatabaseSizeBytes reports the live database size (for the settings readout).
 */
export function GetDatabaseSizeBytes(): Promise<number> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1735793535) as any;
    return $resultPromise;
}

export function GetEnvInfo(): Promise<$models.EnvInfo> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3369643427) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType11($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function GetFilterHistoriesForConnection(connectionID: number): Promise<models$0.FilterHistory[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2941945813, connectionID) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType13($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function GetMatchingSubscriptionForTopic(connId: number, topic: string): Promise<models$0.Subscription | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2749766752, connId, topic) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType2($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function GetMessageHistory(connId: number, topic: string): Promise<mqtt$0.MqttMessage[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3700437937, connId, topic) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType15($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function GetMqttStats(): Promise<$models.MqttStats> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2888945465) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType16($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function GetPanelSizes(): Promise<models$0.PanelSize[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3836927596) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType18($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function GetPublishHistoriesForConnection(connectionID: number): Promise<models$0.PublishHistory[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3102818020, connectionID) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType20($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetReceivedMessageCount returns how many durable messages exist for a topic
 * (drives the window-count UI).
 */
export function GetReceivedMessageCount(connectionID: number, topic: string): Promise<number> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4098527297, connectionID, topic) as any;
    return $resultPromise;
}

/**
 * GetReceivedMessageWindow returns a page of a topic's durable history, always
 * in arrival (ascending) order, via keyset pagination on id:
 * 
 *   - afterID > 0:  the window immediately NEWER than afterID (id > afterID).
 *   - else, beforeID > 0:  the window immediately OLDER than beforeID (id < beforeID).
 *   - both 0:  the newest window.
 * 
 * So "load older" passes the window's smallest id as beforeID; "load newer"
 * passes its largest id as afterID. limit <= 0 uses the default window size.
 */
export function GetReceivedMessageWindow(connectionID: number, topic: string, beforeID: number, afterID: number, limit: number): Promise<mqtt$0.MqttMessage[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2230097254, connectionID, topic, beforeID, afterID, limit) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType15($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function GetSortStates(): Promise<models$0.SortState[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2748919454) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType22($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function LoadOpenTabs(): Promise<models$0.Tab[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2526018972) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType24($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function MoveCollectionMessage(id: number, targetCollectionID: number): Promise<models$0.CollectionMessage> & { cancel(): void } {
    let $resultPromise = $Call.ByID(184359020, id, targetCollectionID) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType6($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function NewConnection(): Promise<$models.Connection | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3098702478) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType26($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * OpenChartWindow opens (or focuses) a separate window rendering the standalone
 * chart for a topic. The new window shares this Go backend and its event
 * stream, so it live-updates from the same messages as the main window.
 */
export function OpenChartWindow(params: $models.OpenChartWindowParams): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1350566632, params) as any;
    return $resultPromise;
}

export function PublishMqtt(connId: number, message: $models.PublishParams): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3575117605, connId, message) as any;
    return $resultPromise;
}

export function RenameCollection(id: number, name: string): Promise<models$0.Collection> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1111441190, id, name) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType5($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function RenameCollectionMessage(id: number, name: string): Promise<models$0.CollectionMessage> & { cancel(): void } {
    let $resultPromise = $Call.ByID(379007077, id, name) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType6($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function SaveCollectionMessage(params: $models.SaveCollectionMessageParams): Promise<models$0.CollectionMessage> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1468270044, params) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType6($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function SaveFilterHistoryEntry(connectionId: number, text: string): Promise<models$0.FilterHistory> & { cancel(): void } {
    let $resultPromise = $Call.ByID(481334387, connectionId, text) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType12($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function SavePublishHistoryEntry(params: $models.SavePublishHistoryEntryParams): Promise<models$0.PublishHistory> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3794014424, params) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType19($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * ServiceStartup is called by Wails when the application starts up
 */
export function ServiceStartup(options: application$0.ServiceOptions): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1191179216, options) as any;
    return $resultPromise;
}

export function StartUpdate(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1435025345) as any;
    return $resultPromise;
}

export function Startup(options: $models.StartupOptions | null): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1674476365, options) as any;
    return $resultPromise;
}

export function UpdateAppSettings(params: $models.UpdateAppSettingsParams): Promise<models$0.AppSettings> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3714588585, params) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType0($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function UpdateConnection(conn: models$0.Connection | null): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2567523649, conn) as any;
    return $resultPromise;
}

export function UpdateOpenConnectionTabs(connIds: number[]): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1501318837, connIds) as any;
    return $resultPromise;
}

export function UpdatePanelSize(panelId: string, size: number, isOpen: boolean): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1524249556, panelId, size, isOpen) as any;
    return $resultPromise;
}

export function UpdateSortState(sortId: string, sortCriteria: string, sortDirection: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2265023050, sortId, sortCriteria, sortDirection) as any;
    return $resultPromise;
}

export function UpdateSubscription(connId: number, sub: models$0.Subscription): Promise<models$0.Subscription | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1582032348, connId, sub) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType2($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

// Private type creation functions
const $$createType0 = models$0.AppSettings.createFrom;
const $$createType1 = models$0.Subscription.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = update$0.UpdateResponse.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = models$0.Collection.createFrom;
const $$createType6 = models$0.CollectionMessage.createFrom;
const $$createType7 = $models.Connections.createFrom;
const $$createType8 = $Create.Array($$createType1);
const $$createType9 = $Create.Map($Create.Any, $$createType8);
const $$createType10 = $Create.Array($$createType5);
const $$createType11 = $models.EnvInfo.createFrom;
const $$createType12 = models$0.FilterHistory.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = mqtt$0.MqttMessage.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = $models.MqttStats.createFrom;
const $$createType17 = models$0.PanelSize.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = models$0.PublishHistory.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = models$0.SortState.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = models$0.Tab.createFrom;
const $$createType24 = $Create.Array($$createType23);
const $$createType25 = $models.Connection.createFrom;
const $$createType26 = $Create.Nullable($$createType25);
