// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mqtt$0 from "../mqtt/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as update$0 from "../update/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AcknowledgeChangelog records that the user has seen the "What's new" dialog
 * for the given app version, so it isn't shown again until the next update.
 */
export function AcknowledgeChangelog(version: string): $CancellablePromise<models$0.AppSettings> {
    return $Call.ByID(3277405218, version).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AcknowledgeStarPrompt records that the user has seen the "star us on GitHub"
 * prompt, so it never shows again (whether they starred or dismissed it).
 */
export function AcknowledgeStarPrompt(): $CancellablePromise<models$0.AppSettings> {
    return $Call.ByID(2492238430).then(($result: any) => {
        return $$createType0($result);
    });
}

export function AddSubscription(connectionId: number): $CancellablePromise<models$0.Subscription | null> {
    return $Call.ByID(1707702138, connectionId).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * AddSysMetricMapping takes the full row (unlike AddSubscription) so
 * "pin as tile" from the raw $SYS browser creates a populated mapping in one
 * call.
 */
export function AddSysMetricMapping(connId: number, mapping: models$0.SysMetricMapping): $CancellablePromise<models$0.SysMetricMapping | null> {
    return $Call.ByID(362334174, connId, mapping).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * Exposed to frontend to call as necessary
 */
export function CheckForUpdates(): $CancellablePromise<update$0.UpdateResponse | null> {
    return $Call.ByID(2570002251).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ChooseCertFile(title: string): $CancellablePromise<string> {
    return $Call.ByID(2632460757, title);
}

export function ChooseDirectory(title: string): $CancellablePromise<string> {
    return $Call.ByID(1399537760, title);
}

export function ClearConnectionHistory(connId: number): $CancellablePromise<void> {
    return $Call.ByID(4129774215, connId);
}

/**
 * ClearReceivedMessages deletes all durable history (optionally for one
 * connection) and compacts the file.
 */
export function ClearReceivedMessages(connectionID: number): $CancellablePromise<void> {
    return $Call.ByID(3528502082, connectionID);
}

export function ConnectMqtt(connId: number): $CancellablePromise<void> {
    return $Call.ByID(1025617036, connId);
}

export function CreateCollection(params: $models.CreateCollectionParams): $CancellablePromise<models$0.Collection> {
    return $Call.ByID(2462867700, params).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * DeleteCollection removes a collection and all messages in it.
 */
export function DeleteCollection(id: number): $CancellablePromise<void> {
    return $Call.ByID(3185313063, id);
}

export function DeleteCollectionMessage(id: number): $CancellablePromise<void> {
    return $Call.ByID(3507400934, id);
}

export function DeleteConnection(id: number): $CancellablePromise<void> {
    return $Call.ByID(4008925183, id);
}

export function DeleteFilterHistoryEntry(connectionId: number, text: string): $CancellablePromise<void> {
    return $Call.ByID(449713245, connectionId, text);
}

export function DeletePublishHistoryEntry(id: number): $CancellablePromise<void> {
    return $Call.ByID(626243294, id);
}

export function DeleteRetainedMessage(connId: number, topic: string): $CancellablePromise<void> {
    return $Call.ByID(1837950630, connId, topic);
}

/**
 * DeleteRetainedMessages clears the retained message on each of the given
 * topics by publishing a zero-length retained payload to it.
 * 
 * It takes an explicit topic list rather than a prefix so the caller clears
 * exactly the topics it counted and showed the user. Re-resolving a prefix here
 * would race live traffic: a topic retained between the confirmation opening
 * and the user accepting it would be swept up silently, making the number they
 * agreed to a lie.
 * 
 * Every topic is attempted even if earlier ones fail, because a half-cleared
 * branch that reports nothing is worse than a full attempt that reports what
 * broke. The error names how many succeeded and how many failed.
 */
export function DeleteRetainedMessages(connId: number, topics: string[]): $CancellablePromise<void> {
    return $Call.ByID(1238327631, connId, topics);
}

export function DeleteSubscription(connId: number, id: number): $CancellablePromise<void> {
    return $Call.ByID(1291658, connId, id);
}

export function DeleteSysMetricMapping(connId: number, id: number): $CancellablePromise<void> {
    return $Call.ByID(3318852174, connId, id);
}

export function DisconnectMqtt(connId: number): $CancellablePromise<void> {
    return $Call.ByID(2595921592, connId);
}

export function DuplicateCollectionMessage(id: number): $CancellablePromise<models$0.CollectionMessage> {
    return $Call.ByID(2896789728, id).then(($result: any) => {
        return $$createType8($result);
    });
}

export function ExportAllMessages(connId: number): $CancellablePromise<string> {
    return $Call.ByID(2360991441, connId);
}

/**
 * ExportAllMessagesData returns the same export as ExportAllMessages but as a
 * JSON string plus default filename, for the browser build to download.
 */
export function ExportAllMessagesData(connId: number): $CancellablePromise<$models.ExportedMessagesPayload> {
    return $Call.ByID(2564244353, connId).then(($result: any) => {
        return $$createType9($result);
    });
}

export function ExportTopicMessages(connId: number, topic: string): $CancellablePromise<string> {
    return $Call.ByID(2895564909, connId, topic);
}

/**
 * ExportTopicMessagesData returns the same export as ExportTopicMessages but as
 * a JSON string plus default filename, for the browser build to download.
 */
export function ExportTopicMessagesData(connId: number, topic: string): $CancellablePromise<$models.ExportedMessagesPayload> {
    return $Call.ByID(711339501, connId, topic).then(($result: any) => {
        return $$createType9($result);
    });
}

export function GetAllConnections(): $CancellablePromise<$models.Connections> {
    return $Call.ByID(3922339528).then(($result: any) => {
        return $$createType10($result);
    });
}

export function GetAllSubscriptionsByConnectionId(): $CancellablePromise<{ [_ in `${number}`]?: models$0.Subscription[] }> {
    return $Call.ByID(3141731323).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * GetAppSettings returns the singleton settings row (seeded by migration).
 */
export function GetAppSettings(): $CancellablePromise<models$0.AppSettings> {
    return $Call.ByID(3769940222).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetCollectionsForConnection returns global collections (connection_id IS NULL)
 * plus collections scoped to the given connection, messages preloaded.
 */
export function GetCollectionsForConnection(connectionID: number): $CancellablePromise<models$0.Collection[]> {
    return $Call.ByID(2553763368, connectionID).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * GetDatabaseSizeBytes reports the live database size (for the settings readout).
 */
export function GetDatabaseSizeBytes(): $CancellablePromise<number> {
    return $Call.ByID(1735793535);
}

export function GetEnvInfo(): $CancellablePromise<$models.EnvInfo> {
    return $Call.ByID(3369643427).then(($result: any) => {
        return $$createType14($result);
    });
}

export function GetFilterHistoriesForConnection(connectionID: number): $CancellablePromise<models$0.FilterHistory[]> {
    return $Call.ByID(2941945813, connectionID).then(($result: any) => {
        return $$createType16($result);
    });
}

export function GetMatchingSubscriptionForTopic(connId: number, topic: string): $CancellablePromise<models$0.Subscription | null> {
    return $Call.ByID(2749766752, connId, topic).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetMessageById fetches a single full message (with its payload) by id from
 * a topic's in-RAM history. timeMs is the message's receive time from its
 * stub; it lets the lookup binary-search the history window instead of
 * scanning it (pass 0 when unknown). found=false (no error) means the message
 * has aged out of the RAM window (evicted by the memory budget), so the
 * frontend can render a graceful "no longer available" state instead of an
 * error.
 */
export function GetMessageById(connId: number, topic: string, id: string, timeMs: number): $CancellablePromise<[mqtt$0.MqttMessage, boolean]> {
    return $Call.ByID(2592571623, connId, topic, id, timeMs).then(($result: any) => {
        $result[0] = $$createType17($result[0]);
        return $result;
    });
}

/**
 * GetMessageHistory returns up to `limit` of the newest retained messages for
 * a topic (limit <= 0 returns everything). The UI passes its window size:
 * returning a busy topic's entire RAM history serializes an unbounded JSON
 * blob across the webview bridge, which crashed the app on huge
 * public-broker topics.
 */
export function GetMessageHistory(connId: number, topic: string, limit: number): $CancellablePromise<mqtt$0.MqttMessage[]> {
    return $Call.ByID(3700437937, connId, topic, limit).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * GetMessageTimeline returns up to `limit` of the newest retained messages
 * for a topic as lightweight stubs (id, timeMs, qos, retain, no payload).
 * This is the memory-mode counterpart to GetReceivedTimelineWindow: selecting
 * a topic fetches stubs to draw the timeline, then fetches individual
 * payloads on demand via GetMessageById.
 */
export function GetMessageTimeline(connId: number, topic: string, limit: number): $CancellablePromise<mqtt$0.MqttMessageStub[]> {
    return $Call.ByID(3329510004, connId, topic, limit).then(($result: any) => {
        return $$createType20($result);
    });
}

/**
 * GetMessagesByIds fetches a batch of full messages (with payloads) by id
 * from a topic's in-RAM history. ids and timesMs are parallel slices (the
 * stubs' receive times drive the same fast lookup as GetMessageById). Only
 * the messages still retained are returned; the frontend treats any omitted
 * id as aged out.
 */
export function GetMessagesByIds(connId: number, topic: string, ids: string[], timesMs: number[]): $CancellablePromise<mqtt$0.MqttMessage[]> {
    return $Call.ByID(1309585445, connId, topic, ids, timesMs).then(($result: any) => {
        return $$createType18($result);
    });
}

export function GetMqttStats(): $CancellablePromise<$models.MqttStats> {
    return $Call.ByID(2888945465).then(($result: any) => {
        return $$createType21($result);
    });
}

export function GetPanelSizes(): $CancellablePromise<models$0.PanelSize[]> {
    return $Call.ByID(3836927596).then(($result: any) => {
        return $$createType23($result);
    });
}

export function GetPublishHistoriesForConnection(connectionID: number): $CancellablePromise<models$0.PublishHistory[]> {
    return $Call.ByID(3102818020, connectionID).then(($result: any) => {
        return $$createType25($result);
    });
}

/**
 * GetReceivedMessageById fetches a single durable message (with its full
 * payload) by numeric row id, scoped to the connection/topic. Used for the
 * on-demand payload fetch when a timeline stub is selected or clicked.
 * found=false (no error) means the row no longer exists (e.g. pruned), so the
 * frontend can render a graceful "no longer available" state.
 */
export function GetReceivedMessageById(connectionID: number, topic: string, id: number): $CancellablePromise<[mqtt$0.MqttMessage, boolean]> {
    return $Call.ByID(2888436030, connectionID, topic, id).then(($result: any) => {
        $result[0] = $$createType17($result[0]);
        return $result;
    });
}

/**
 * GetReceivedMessageCount returns how many durable messages exist for a topic
 * (drives the window-count UI).
 */
export function GetReceivedMessageCount(connectionID: number, topic: string): $CancellablePromise<number> {
    return $Call.ByID(4098527297, connectionID, topic);
}

/**
 * GetReceivedMessageWindow returns a page of a topic's durable history, always
 * in arrival (ascending) order, via keyset pagination on id:
 * 
 *   - afterID > 0:  the window immediately NEWER than afterID (id > afterID).
 *   - else, beforeID > 0:  the window immediately OLDER than beforeID (id < beforeID).
 *   - both 0:  the newest window.
 * 
 * So "load older" passes the window's smallest id as beforeID; "load newer"
 * passes its largest id as afterID. limit <= 0 uses the default window size.
 */
export function GetReceivedMessageWindow(connectionID: number, topic: string, beforeID: number, afterID: number, limit: number): $CancellablePromise<mqtt$0.MqttMessage[]> {
    return $Call.ByID(2230097254, connectionID, topic, beforeID, afterID, limit).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * GetReceivedMessagesByIds fetches a batch of durable messages (with full
 * payloads) by numeric row id, scoped to the connection/topic, in ascending
 * id order. Ids with no matching row are simply omitted from the result, so
 * the frontend can treat them as pruned ("aged out").
 */
export function GetReceivedMessagesByIds(connectionID: number, topic: string, ids: number[]): $CancellablePromise<mqtt$0.MqttMessage[]> {
    return $Call.ByID(508166040, connectionID, topic, ids).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * GetReceivedTimelineWindow mirrors GetReceivedMessageWindow's keyset paging
 * (same beforeID/afterID/limit semantics) but selects only the stub columns
 * (id, timeMs, qos, retain), never the payload. This is what the timeline
 * pages through when browsing a busy topic's durable history: a window of
 * 5000 stubs is a few hundred KB at most, versus potentially tens of MB if
 * every row's payload were included.
 */
export function GetReceivedTimelineWindow(connectionID: number, topic: string, beforeID: number, afterID: number, limit: number): $CancellablePromise<mqtt$0.MqttMessageStub[]> {
    return $Call.ByID(3455009092, connectionID, topic, beforeID, afterID, limit).then(($result: any) => {
        return $$createType20($result);
    });
}

/**
 * GetRetainedTopicsUnderPrefix returns the known-retained topics at or below a
 * topic prefix, sorted. It backs the count shown before a bulk retained
 * cleanup.
 * 
 * "Known" is doing real work here: this reflects the retained messages this
 * session has seen, not the broker's true retained set (see
 * mqtt.MessageHistory's retained field). UI copy must not present it as
 * complete.
 */
export function GetRetainedTopicsUnderPrefix(connId: number, prefix: string): $CancellablePromise<string[]> {
    return $Call.ByID(570234138, connId, prefix).then(($result: any) => {
        return $$createType26($result);
    });
}

export function GetSortStates(): $CancellablePromise<models$0.SortState[]> {
    return $Call.ByID(2748919454).then(($result: any) => {
        return $$createType28($result);
    });
}

/**
 * GetSysMessageHistory returns every retained $SYS/* message for a
 * connection, flattened across topics and sorted by arrival time, so a
 * broker-status window opened mid-session starts populated.
 */
export function GetSysMessageHistory(connId: number): $CancellablePromise<mqtt$0.MqttMessage[]> {
    return $Call.ByID(2117163184, connId).then(($result: any) => {
        return $$createType18($result);
    });
}

export function GetSysMetricMappingsByConnectionId(connId: number): $CancellablePromise<models$0.SysMetricMapping[]> {
    return $Call.ByID(1443899974, connId).then(($result: any) => {
        return $$createType29($result);
    });
}

export function LoadOpenTabs(): $CancellablePromise<models$0.Tab[]> {
    return $Call.ByID(2526018972).then(($result: any) => {
        return $$createType31($result);
    });
}

export function MoveCollectionMessage(id: number, targetCollectionID: number): $CancellablePromise<models$0.CollectionMessage> {
    return $Call.ByID(184359020, id, targetCollectionID).then(($result: any) => {
        return $$createType8($result);
    });
}

export function NewConnection(): $CancellablePromise<$models.Connection | null> {
    return $Call.ByID(3098702478).then(($result: any) => {
        return $$createType33($result);
    });
}

/**
 * OpenBrokerStatusWindow opens (or focuses) the detached broker-status window
 * for a connection. The new window shares this Go backend and its event
 * stream, so it live-updates from the same messages as the main window.
 */
export function OpenBrokerStatusWindow(connectionId: number): $CancellablePromise<void> {
    return $Call.ByID(3759200119, connectionId);
}

/**
 * OpenChartWindow opens (or focuses) a separate window rendering the standalone
 * chart for a topic. The new window shares this Go backend and its event
 * stream, so it live-updates from the same messages as the main window.
 */
export function OpenChartWindow(params: $models.OpenChartWindowParams): $CancellablePromise<void> {
    return $Call.ByID(1350566632, params);
}

export function PublishMqtt(connId: number, message: $models.PublishParams): $CancellablePromise<void> {
    return $Call.ByID(3575117605, connId, message);
}

export function RenameCollection(id: number, name: string): $CancellablePromise<models$0.Collection> {
    return $Call.ByID(1111441190, id, name).then(($result: any) => {
        return $$createType7($result);
    });
}

export function RenameCollectionMessage(id: number, name: string): $CancellablePromise<models$0.CollectionMessage> {
    return $Call.ByID(379007077, id, name).then(($result: any) => {
        return $$createType8($result);
    });
}

export function SaveCollectionMessage(params: $models.SaveCollectionMessageParams): $CancellablePromise<models$0.CollectionMessage> {
    return $Call.ByID(1468270044, params).then(($result: any) => {
        return $$createType8($result);
    });
}

export function SaveFilterHistoryEntry(connectionId: number, text: string): $CancellablePromise<models$0.FilterHistory> {
    return $Call.ByID(481334387, connectionId, text).then(($result: any) => {
        return $$createType15($result);
    });
}

export function SavePublishHistoryEntry(params: $models.SavePublishHistoryEntryParams): $CancellablePromise<models$0.PublishHistory> {
    return $Call.ByID(3794014424, params).then(($result: any) => {
        return $$createType24($result);
    });
}

export function StartUpdate(): $CancellablePromise<void> {
    return $Call.ByID(1435025345);
}

export function Startup(options: $models.StartupOptions | null): $CancellablePromise<void> {
    return $Call.ByID(1674476365, options);
}

export function UpdateAppSettings(params: $models.UpdateAppSettingsParams): $CancellablePromise<models$0.AppSettings> {
    return $Call.ByID(3714588585, params).then(($result: any) => {
        return $$createType0($result);
    });
}

export function UpdateConnection(conn: models$0.Connection | null): $CancellablePromise<void> {
    return $Call.ByID(2567523649, conn);
}

export function UpdateOpenConnectionTabs(connIds: number[]): $CancellablePromise<void> {
    return $Call.ByID(1501318837, connIds);
}

export function UpdatePanelSize(panelId: string, size: number, isOpen: boolean): $CancellablePromise<void> {
    return $Call.ByID(1524249556, panelId, size, isOpen);
}

export function UpdateSortState(sortId: string, sortCriteria: string, sortDirection: string): $CancellablePromise<void> {
    return $Call.ByID(2265023050, sortId, sortCriteria, sortDirection);
}

export function UpdateSubscription(connId: number, sub: models$0.Subscription): $CancellablePromise<models$0.Subscription | null> {
    return $Call.ByID(1582032348, connId, sub).then(($result: any) => {
        return $$createType2($result);
    });
}

export function UpdateSysMetricMapping(connId: number, mapping: models$0.SysMetricMapping): $CancellablePromise<models$0.SysMetricMapping | null> {
    return $Call.ByID(1283760572, connId, mapping).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = models$0.AppSettings.createFrom;
const $$createType1 = models$0.Subscription.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = models$0.SysMetricMapping.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = update$0.UpdateResponse.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = models$0.Collection.createFrom;
const $$createType8 = models$0.CollectionMessage.createFrom;
const $$createType9 = $models.ExportedMessagesPayload.createFrom;
const $$createType10 = $models.Connections.createFrom;
const $$createType11 = $Create.Array($$createType1);
const $$createType12 = $Create.Map($Create.Any, $$createType11);
const $$createType13 = $Create.Array($$createType7);
const $$createType14 = $models.EnvInfo.createFrom;
const $$createType15 = models$0.FilterHistory.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = mqtt$0.MqttMessage.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = mqtt$0.MqttMessageStub.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = $models.MqttStats.createFrom;
const $$createType22 = models$0.PanelSize.createFrom;
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = models$0.PublishHistory.createFrom;
const $$createType25 = $Create.Array($$createType24);
const $$createType26 = $Create.Array($Create.Any);
const $$createType27 = models$0.SortState.createFrom;
const $$createType28 = $Create.Array($$createType27);
const $$createType29 = $Create.Array($$createType3);
const $$createType30 = models$0.Tab.createFrom;
const $$createType31 = $Create.Array($$createType30);
const $$createType32 = $models.Connection.createFrom;
const $$createType33 = $Create.Nullable($$createType32);
