// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mqtt$0 from "../mqtt/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as paths$0 from "../paths/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as events$0 from "../../events/models.js";

/**
 * Used to represent a connection in the frontend
 */
export class Connection {
    "connectionDetails": models$0.Connection;
    "isConnected": boolean;
    "eventSet": events$0.ConnectionEventsSet;

    /** Creates a new Connection instance. */
    constructor($$source: Partial<Connection> = {}) {
        if (!("connectionDetails" in $$source)) {
            this["connectionDetails"] = (new models$0.Connection());
        }
        if (!("isConnected" in $$source)) {
            this["isConnected"] = false;
        }
        if (!("eventSet" in $$source)) {
            this["eventSet"] = (new events$0.ConnectionEventsSet());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Connection instance from a string or object.
     */
    static createFrom($$source: any = {}): Connection {
        const $$createField0_0 = $$createType0;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("connectionDetails" in $$parsedSource) {
            $$parsedSource["connectionDetails"] = $$createField0_0($$parsedSource["connectionDetails"]);
        }
        if ("eventSet" in $$parsedSource) {
            $$parsedSource["eventSet"] = $$createField2_0($$parsedSource["eventSet"]);
        }
        return new Connection($$parsedSource as Partial<Connection>);
    }
}

export class Connections {
    "connections": { [_: `${number}`]: Connection };

    /** Creates a new Connections instance. */
    constructor($$source: Partial<Connections> = {}) {
        if (!("connections" in $$source)) {
            this["connections"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Connections instance from a string or object.
     */
    static createFrom($$source: any = {}): Connections {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("connections" in $$parsedSource) {
            $$parsedSource["connections"] = $$createField0_0($$parsedSource["connections"]);
        }
        return new Connections($$parsedSource as Partial<Connections>);
    }
}

export class CreateCollectionParams {
    "name": string;

    /**
     * nil = global collection
     */
    "connectionId": number | null;

    /** Creates a new CreateCollectionParams instance. */
    constructor($$source: Partial<CreateCollectionParams> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("connectionId" in $$source)) {
            this["connectionId"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateCollectionParams instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateCollectionParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateCollectionParams($$parsedSource as Partial<CreateCollectionParams>);
    }
}

export class EnvInfo {
    "isDev": boolean;
    "serverAddress": string;
    "version": string;

    /** Creates a new EnvInfo instance. */
    constructor($$source: Partial<EnvInfo> = {}) {
        if (!("isDev" in $$source)) {
            this["isDev"] = false;
        }
        if (!("serverAddress" in $$source)) {
            this["serverAddress"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): EnvInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EnvInfo($$parsedSource as Partial<EnvInfo>);
    }
}

export class MqttStats {
    "totalMessagesReceived": number;
    "totalMessagesSent": number;
    "totalBytesReceived": number;
    "totalBytesSent": number;
    "statsByConnection": { [_: `${number}`]: mqtt$0.ConnectionStats };

    /** Creates a new MqttStats instance. */
    constructor($$source: Partial<MqttStats> = {}) {
        if (!("totalMessagesReceived" in $$source)) {
            this["totalMessagesReceived"] = 0;
        }
        if (!("totalMessagesSent" in $$source)) {
            this["totalMessagesSent"] = 0;
        }
        if (!("totalBytesReceived" in $$source)) {
            this["totalBytesReceived"] = 0;
        }
        if (!("totalBytesSent" in $$source)) {
            this["totalBytesSent"] = 0;
        }
        if (!("statsByConnection" in $$source)) {
            this["statsByConnection"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MqttStats instance from a string or object.
     */
    static createFrom($$source: any = {}): MqttStats {
        const $$createField4_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("statsByConnection" in $$parsedSource) {
            $$parsedSource["statsByConnection"] = $$createField4_0($$parsedSource["statsByConnection"]);
        }
        return new MqttStats($$parsedSource as Partial<MqttStats>);
    }
}

/**
 * OpenChartWindowParams carries the state needed to render a detached chart:
 * which connection + topic, and the numeric field paths to plot.
 */
export class OpenChartWindowParams {
    "connectionId": number;
    "topic": string;
    "fields": string[];

    /** Creates a new OpenChartWindowParams instance. */
    constructor($$source: Partial<OpenChartWindowParams> = {}) {
        if (!("connectionId" in $$source)) {
            this["connectionId"] = 0;
        }
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("fields" in $$source)) {
            this["fields"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenChartWindowParams instance from a string or object.
     */
    static createFrom($$source: any = {}): OpenChartWindowParams {
        const $$createField2_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fields" in $$parsedSource) {
            $$parsedSource["fields"] = $$createField2_0($$parsedSource["fields"]);
        }
        return new OpenChartWindowParams($$parsedSource as Partial<OpenChartWindowParams>);
    }
}

/**
 * ProtoStateResult is the read model the frontend polls (on dialog open,
 * after a dir pick, and on ProtoStateChanged) to render the bindings form
 * and publish panel. Dir/LoadError/FileDescriptors/DescriptorNames describe
 * the compiled per-connection registry (all zero values until one loads
 * successfully); Rules is always the live DB row set.
 */
export class ProtoStateResult {
    "dir": string;
    "loadError": string;
    "dirMissing": boolean;
    "fileDescriptors": { [_: string]: string[] };
    "descriptorNames": string[];
    "rules": models$0.ProtoBindingRule[];

    /** Creates a new ProtoStateResult instance. */
    constructor($$source: Partial<ProtoStateResult> = {}) {
        if (!("dir" in $$source)) {
            this["dir"] = "";
        }
        if (!("loadError" in $$source)) {
            this["loadError"] = "";
        }
        if (!("dirMissing" in $$source)) {
            this["dirMissing"] = false;
        }
        if (!("fileDescriptors" in $$source)) {
            this["fileDescriptors"] = {};
        }
        if (!("descriptorNames" in $$source)) {
            this["descriptorNames"] = [];
        }
        if (!("rules" in $$source)) {
            this["rules"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProtoStateResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ProtoStateResult {
        const $$createField3_0 = $$createType7;
        const $$createField4_0 = $$createType6;
        const $$createField5_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fileDescriptors" in $$parsedSource) {
            $$parsedSource["fileDescriptors"] = $$createField3_0($$parsedSource["fileDescriptors"]);
        }
        if ("descriptorNames" in $$parsedSource) {
            $$parsedSource["descriptorNames"] = $$createField4_0($$parsedSource["descriptorNames"]);
        }
        if ("rules" in $$parsedSource) {
            $$parsedSource["rules"] = $$createField5_0($$parsedSource["rules"]);
        }
        return new ProtoStateResult($$parsedSource as Partial<ProtoStateResult>);
    }
}

export class PublishParams {
    "topic": string;
    "qos": number;
    "payload": string;
    "retain": boolean;
    "properties": PublishProperties;

    /**
     * nil = auto (matcher decides), "" = raw (skip protobuf encoding),
     * "<name>" = forced message type.
     */
    "protoOverride": string | null;

    /** Creates a new PublishParams instance. */
    constructor($$source: Partial<PublishParams> = {}) {
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("qos" in $$source)) {
            this["qos"] = 0;
        }
        if (!("payload" in $$source)) {
            this["payload"] = "";
        }
        if (!("retain" in $$source)) {
            this["retain"] = false;
        }
        if (!("properties" in $$source)) {
            this["properties"] = (new PublishProperties());
        }
        if (!("protoOverride" in $$source)) {
            this["protoOverride"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublishParams instance from a string or object.
     */
    static createFrom($$source: any = {}): PublishParams {
        const $$createField4_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("properties" in $$parsedSource) {
            $$parsedSource["properties"] = $$createField4_0($$parsedSource["properties"]);
        }
        return new PublishParams($$parsedSource as Partial<PublishParams>);
    }
}

export class PublishProperties {
    "contentType"?: string;
    "payloadFormatIndicator": boolean;
    "messageExpiryInterval"?: number;
    "topicAlias"?: number;
    "responseTopic"?: string;
    "correlationData"?: string;
    "subscriptionIdentifier"?: number;
    "userProperties"?: { [_: string]: string };

    /** Creates a new PublishProperties instance. */
    constructor($$source: Partial<PublishProperties> = {}) {
        if (!("payloadFormatIndicator" in $$source)) {
            this["payloadFormatIndicator"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublishProperties instance from a string or object.
     */
    static createFrom($$source: any = {}): PublishProperties {
        const $$createField7_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("userProperties" in $$parsedSource) {
            $$parsedSource["userProperties"] = $$createField7_0($$parsedSource["userProperties"]);
        }
        return new PublishProperties($$parsedSource as Partial<PublishProperties>);
    }
}

export class SaveCollectionMessageParams {
    /**
     * nil = create new message, otherwise update existing
     */
    "id": number | null;
    "collectionId": number;
    "name": string;
    "topic": string;
    "payload": string;
    "qos": number;
    "retain": boolean;
    "encoding": string;
    "format": string;
    "headerContentType": string | null;
    "headerResponseTopic": string | null;
    "headerCorrelationData": string | null;
    "headerPayloadFormatIndicator": boolean | null;
    "headerMessageExpiryInterval": number | null;
    "headerTopicAlias": number | null;
    "headerSubscriptionIdentifier": number | null;
    "userProperties": string | null;
    "protoOverride": string | null;

    /** Creates a new SaveCollectionMessageParams instance. */
    constructor($$source: Partial<SaveCollectionMessageParams> = {}) {
        if (!("id" in $$source)) {
            this["id"] = null;
        }
        if (!("collectionId" in $$source)) {
            this["collectionId"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("payload" in $$source)) {
            this["payload"] = "";
        }
        if (!("qos" in $$source)) {
            this["qos"] = 0;
        }
        if (!("retain" in $$source)) {
            this["retain"] = false;
        }
        if (!("encoding" in $$source)) {
            this["encoding"] = "";
        }
        if (!("format" in $$source)) {
            this["format"] = "";
        }
        if (!("headerContentType" in $$source)) {
            this["headerContentType"] = null;
        }
        if (!("headerResponseTopic" in $$source)) {
            this["headerResponseTopic"] = null;
        }
        if (!("headerCorrelationData" in $$source)) {
            this["headerCorrelationData"] = null;
        }
        if (!("headerPayloadFormatIndicator" in $$source)) {
            this["headerPayloadFormatIndicator"] = null;
        }
        if (!("headerMessageExpiryInterval" in $$source)) {
            this["headerMessageExpiryInterval"] = null;
        }
        if (!("headerTopicAlias" in $$source)) {
            this["headerTopicAlias"] = null;
        }
        if (!("headerSubscriptionIdentifier" in $$source)) {
            this["headerSubscriptionIdentifier"] = null;
        }
        if (!("userProperties" in $$source)) {
            this["userProperties"] = null;
        }
        if (!("protoOverride" in $$source)) {
            this["protoOverride"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveCollectionMessageParams instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveCollectionMessageParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SaveCollectionMessageParams($$parsedSource as Partial<SaveCollectionMessageParams>);
    }
}

export class SavePublishHistoryEntryParams {
    "connectionId": number;
    "topic": string;
    "payload": string;
    "qos": number;
    "retain": boolean;
    "encoding": string;
    "format": string;
    "headerContentType": string | null;
    "headerResponseTopic": string | null;
    "headerCorrelationData": string | null;
    "headerPayloadFormatIndicator": boolean | null;
    "headerMessageExpiryInterval": number | null;
    "headerTopicAlias": number | null;
    "headerSubscriptionIdentifier": number | null;
    "userProperties": string | null;
    "protoOverride": string | null;

    /** Creates a new SavePublishHistoryEntryParams instance. */
    constructor($$source: Partial<SavePublishHistoryEntryParams> = {}) {
        if (!("connectionId" in $$source)) {
            this["connectionId"] = 0;
        }
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("payload" in $$source)) {
            this["payload"] = "";
        }
        if (!("qos" in $$source)) {
            this["qos"] = 0;
        }
        if (!("retain" in $$source)) {
            this["retain"] = false;
        }
        if (!("encoding" in $$source)) {
            this["encoding"] = "";
        }
        if (!("format" in $$source)) {
            this["format"] = "";
        }
        if (!("headerContentType" in $$source)) {
            this["headerContentType"] = null;
        }
        if (!("headerResponseTopic" in $$source)) {
            this["headerResponseTopic"] = null;
        }
        if (!("headerCorrelationData" in $$source)) {
            this["headerCorrelationData"] = null;
        }
        if (!("headerPayloadFormatIndicator" in $$source)) {
            this["headerPayloadFormatIndicator"] = null;
        }
        if (!("headerMessageExpiryInterval" in $$source)) {
            this["headerMessageExpiryInterval"] = null;
        }
        if (!("headerTopicAlias" in $$source)) {
            this["headerTopicAlias"] = null;
        }
        if (!("headerSubscriptionIdentifier" in $$source)) {
            this["headerSubscriptionIdentifier"] = null;
        }
        if (!("userProperties" in $$source)) {
            this["userProperties"] = null;
        }
        if (!("protoOverride" in $$source)) {
            this["protoOverride"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SavePublishHistoryEntryParams instance from a string or object.
     */
    static createFrom($$source: any = {}): SavePublishHistoryEntryParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SavePublishHistoryEntryParams($$parsedSource as Partial<SavePublishHistoryEntryParams>);
    }
}

export class StartupOptions {
    "PathsOverride": paths$0.Paths | null;
    "DbNameOverride": string | null;

    /** Creates a new StartupOptions instance. */
    constructor($$source: Partial<StartupOptions> = {}) {
        if (!("PathsOverride" in $$source)) {
            this["PathsOverride"] = null;
        }
        if (!("DbNameOverride" in $$source)) {
            this["DbNameOverride"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartupOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): StartupOptions {
        const $$createField0_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("PathsOverride" in $$parsedSource) {
            $$parsedSource["PathsOverride"] = $$createField0_0($$parsedSource["PathsOverride"]);
        }
        return new StartupOptions($$parsedSource as Partial<StartupOptions>);
    }
}

export class UpdateAppSettingsParams {
    "memoryBudgetBytes": number;
    "recordingEnabled": boolean;
    "diskBudgetBytes": number;
    "hasSeenHistoryPrompt": boolean;

    /** Creates a new UpdateAppSettingsParams instance. */
    constructor($$source: Partial<UpdateAppSettingsParams> = {}) {
        if (!("memoryBudgetBytes" in $$source)) {
            this["memoryBudgetBytes"] = 0;
        }
        if (!("recordingEnabled" in $$source)) {
            this["recordingEnabled"] = false;
        }
        if (!("diskBudgetBytes" in $$source)) {
            this["diskBudgetBytes"] = 0;
        }
        if (!("hasSeenHistoryPrompt" in $$source)) {
            this["hasSeenHistoryPrompt"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateAppSettingsParams instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateAppSettingsParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateAppSettingsParams($$parsedSource as Partial<UpdateAppSettingsParams>);
    }
}

// Private type creation functions
const $$createType0 = models$0.Connection.createFrom;
const $$createType1 = events$0.ConnectionEventsSet.createFrom;
const $$createType2 = Connection.createFrom;
const $$createType3 = $Create.Map($Create.Any, $$createType2);
const $$createType4 = mqtt$0.ConnectionStats.createFrom;
const $$createType5 = $Create.Map($Create.Any, $$createType4);
const $$createType6 = $Create.Array($Create.Any);
const $$createType7 = $Create.Map($Create.Any, $$createType6);
const $$createType8 = models$0.ProtoBindingRule.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = PublishProperties.createFrom;
const $$createType11 = $Create.Map($Create.Any, $Create.Any);
const $$createType12 = paths$0.Paths.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
