// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class ProtoBindingMatch {
    "MessageType": string;
    "Filter": string;
    "Source": string;

    /** Creates a new ProtoBindingMatch instance. */
    constructor($$source: Partial<ProtoBindingMatch> = {}) {
        if (!("MessageType" in $$source)) {
            this["MessageType"] = "";
        }
        if (!("Filter" in $$source)) {
            this["Filter"] = "";
        }
        if (!("Source" in $$source)) {
            this["Source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProtoBindingMatch instance from a string or object.
     */
    static createFrom($$source: any = {}): ProtoBindingMatch {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProtoBindingMatch($$parsedSource as Partial<ProtoBindingMatch>);
    }
}
