// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as null$0 from "../../../gopkg.in/guregu/null.v4/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export class Connection {
    "id": number;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;
    "name": string;
    "mqttVersion": string;
    "hasCustomClientId": boolean | null;
    "clientId": null$0.String;
    "protocol": string;
    "host": string;
    "port": number;
    "websocketPath": string;
    "username": null$0.String;
    "password": null$0.String;
    "isProtoEnabled": boolean | null;
    "isCertsEnabled": boolean | null;
    "skipCertVerification": boolean | null;
    "certCa": null$0.String;
    "certClient": null$0.String;
    "certClientKey": null$0.String;
    "subscriptions": Subscription[];
    "lastConnectedAt": null$0.Time;
    "customIconSeed": null$0.String;
    "filterHistories": FilterHistory[];
    "publishHistories": PublishHistory[];

    /** Creates a new Connection instance. */
    constructor($$source: Partial<Connection> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("mqttVersion" in $$source)) {
            this["mqttVersion"] = "";
        }
        if (!("hasCustomClientId" in $$source)) {
            this["hasCustomClientId"] = null;
        }
        if (!("clientId" in $$source)) {
            this["clientId"] = null;
        }
        if (!("protocol" in $$source)) {
            this["protocol"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("websocketPath" in $$source)) {
            this["websocketPath"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = null;
        }
        if (!("password" in $$source)) {
            this["password"] = null;
        }
        if (!("isProtoEnabled" in $$source)) {
            this["isProtoEnabled"] = null;
        }
        if (!("isCertsEnabled" in $$source)) {
            this["isCertsEnabled"] = null;
        }
        if (!("skipCertVerification" in $$source)) {
            this["skipCertVerification"] = null;
        }
        if (!("certCa" in $$source)) {
            this["certCa"] = null;
        }
        if (!("certClient" in $$source)) {
            this["certClient"] = null;
        }
        if (!("certClientKey" in $$source)) {
            this["certClientKey"] = null;
        }
        if (!("subscriptions" in $$source)) {
            this["subscriptions"] = [];
        }
        if (!("lastConnectedAt" in $$source)) {
            this["lastConnectedAt"] = null;
        }
        if (!("customIconSeed" in $$source)) {
            this["customIconSeed"] = null;
        }
        if (!("filterHistories" in $$source)) {
            this["filterHistories"] = [];
        }
        if (!("publishHistories" in $$source)) {
            this["publishHistories"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Connection instance from a string or object.
     */
    static createFrom($$source: any = {}): Connection {
        const $$createField19_0 = $$createType1;
        const $$createField22_0 = $$createType3;
        const $$createField23_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("subscriptions" in $$parsedSource) {
            $$parsedSource["subscriptions"] = $$createField19_0($$parsedSource["subscriptions"]);
        }
        if ("filterHistories" in $$parsedSource) {
            $$parsedSource["filterHistories"] = $$createField22_0($$parsedSource["filterHistories"]);
        }
        if ("publishHistories" in $$parsedSource) {
            $$parsedSource["publishHistories"] = $$createField23_0($$parsedSource["publishHistories"]);
        }
        return new Connection($$parsedSource as Partial<Connection>);
    }
}

export class FilterHistory {
    "id": number;
    "connectionId": number;
    "text": string;
    "lastUsed": time$0.Time;

    /** Creates a new FilterHistory instance. */
    constructor($$source: Partial<FilterHistory> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("connectionId" in $$source)) {
            this["connectionId"] = 0;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("lastUsed" in $$source)) {
            this["lastUsed"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FilterHistory instance from a string or object.
     */
    static createFrom($$source: any = {}): FilterHistory {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FilterHistory($$parsedSource as Partial<FilterHistory>);
    }
}

export class PanelSize {
    "id": string;
    "size": number;
    "isOpen": boolean;

    /** Creates a new PanelSize instance. */
    constructor($$source: Partial<PanelSize> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("isOpen" in $$source)) {
            this["isOpen"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PanelSize instance from a string or object.
     */
    static createFrom($$source: any = {}): PanelSize {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PanelSize($$parsedSource as Partial<PanelSize>);
    }
}

export class PublishHistory {
    "id": number;
    "connectionId": number;
    "topic": string;
    "qos": number;
    "retain": boolean;
    "payload": string;
    "encoding": string;
    "format": string;

    /**
     * JSON key-value properties stored as string
     */
    "userProperties": string | null;
    "headerContentType": string | null;
    "headerResponseTopic": string | null;
    "headerCorrelationData": string | null;
    "headerPayloadFormatIndicator": boolean | null;
    "headerMessageExpiryInterval": number | null;
    "headerTopicAlias": number | null;
    "headerSubscriptionIdentifier": number | null;
    "publishedAt": time$0.Time;

    /** Creates a new PublishHistory instance. */
    constructor($$source: Partial<PublishHistory> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("connectionId" in $$source)) {
            this["connectionId"] = 0;
        }
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("qos" in $$source)) {
            this["qos"] = 0;
        }
        if (!("retain" in $$source)) {
            this["retain"] = false;
        }
        if (!("payload" in $$source)) {
            this["payload"] = "";
        }
        if (!("encoding" in $$source)) {
            this["encoding"] = "";
        }
        if (!("format" in $$source)) {
            this["format"] = "";
        }
        if (!("userProperties" in $$source)) {
            this["userProperties"] = null;
        }
        if (!("headerContentType" in $$source)) {
            this["headerContentType"] = null;
        }
        if (!("headerResponseTopic" in $$source)) {
            this["headerResponseTopic"] = null;
        }
        if (!("headerCorrelationData" in $$source)) {
            this["headerCorrelationData"] = null;
        }
        if (!("headerPayloadFormatIndicator" in $$source)) {
            this["headerPayloadFormatIndicator"] = null;
        }
        if (!("headerMessageExpiryInterval" in $$source)) {
            this["headerMessageExpiryInterval"] = null;
        }
        if (!("headerTopicAlias" in $$source)) {
            this["headerTopicAlias"] = null;
        }
        if (!("headerSubscriptionIdentifier" in $$source)) {
            this["headerSubscriptionIdentifier"] = null;
        }
        if (!("publishedAt" in $$source)) {
            this["publishedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublishHistory instance from a string or object.
     */
    static createFrom($$source: any = {}): PublishHistory {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PublishHistory($$parsedSource as Partial<PublishHistory>);
    }
}

export class SortState {
    "id": string;
    "sortCriteria": string;
    "sortDirection": string;

    /** Creates a new SortState instance. */
    constructor($$source: Partial<SortState> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("sortCriteria" in $$source)) {
            this["sortCriteria"] = "";
        }
        if (!("sortDirection" in $$source)) {
            this["sortDirection"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SortState instance from a string or object.
     */
    static createFrom($$source: any = {}): SortState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SortState($$parsedSource as Partial<SortState>);
    }
}

export class Subscription {
    "id": number;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;
    "connectionId": number;
    "qos": number | null;
    "topic": string;

    /** Creates a new Subscription instance. */
    constructor($$source: Partial<Subscription> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }
        if (!("connectionId" in $$source)) {
            this["connectionId"] = 0;
        }
        if (!("qos" in $$source)) {
            this["qos"] = null;
        }
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Subscription instance from a string or object.
     */
    static createFrom($$source: any = {}): Subscription {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Subscription($$parsedSource as Partial<Subscription>);
    }
}

export class Tab {
    "id": number;
    "tabIndex": number;
    "connectionId": number;
    "connection": Connection;

    /** Creates a new Tab instance. */
    constructor($$source: Partial<Tab> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("tabIndex" in $$source)) {
            this["tabIndex"] = 0;
        }
        if (!("connectionId" in $$source)) {
            this["connectionId"] = 0;
        }
        if (!("connection" in $$source)) {
            this["connection"] = (new Connection());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Tab instance from a string or object.
     */
    static createFrom($$source: any = {}): Tab {
        const $$createField3_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("connection" in $$parsedSource) {
            $$parsedSource["connection"] = $$createField3_0($$parsedSource["connection"]);
        }
        return new Tab($$parsedSource as Partial<Tab>);
    }
}

// Private type creation functions
const $$createType0 = Subscription.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = FilterHistory.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = PublishHistory.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = Connection.createFrom;
