// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class Paths {
    "ResourcePath": string;

    /** Creates a new Paths instance. */
    constructor($$source: Partial<Paths> = {}) {
        if (!("ResourcePath" in $$source)) {
            this["ResourcePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Paths instance from a string or object.
     */
    static createFrom($$source: any = {}): Paths {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Paths($$parsedSource as Partial<Paths>);
    }
}
