// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class UpdateResponse {
    "machine_id": string;
    "latest_version": string;

    /**
     * marked as false if license is not valid for this update
     */
    "can_update": boolean;
    "release_notes": string;
    "notification_text": string;
    "notification_url": string;

    /**
     * Empty if cannot update
     */
    "update_url": string;

    /** Creates a new UpdateResponse instance. */
    constructor($$source: Partial<UpdateResponse> = {}) {
        if (!("machine_id" in $$source)) {
            this["machine_id"] = "";
        }
        if (!("latest_version" in $$source)) {
            this["latest_version"] = "";
        }
        if (!("can_update" in $$source)) {
            this["can_update"] = false;
        }
        if (!("release_notes" in $$source)) {
            this["release_notes"] = "";
        }
        if (!("notification_text" in $$source)) {
            this["notification_text"] = "";
        }
        if (!("notification_url" in $$source)) {
            this["notification_url"] = "";
        }
        if (!("update_url" in $$source)) {
            this["update_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateResponse($$parsedSource as Partial<UpdateResponse>);
    }
}
