// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

/**
 * UpdateResponse is what the frontend receives when an update is available.
 * There is no licensing, so an update is always offered when a newer version
 * exists. CanSelfUpdate decides whether the app updates itself through the
 * built-in updater or the user follows install-type-specific instructions.
 */
export class UpdateResponse {
    "latest_version": string;
    "release_notes": string;
    "can_self_update": boolean;
    "install_type": string;
    "update_command": string;
    "instructions": string;
    "releases_url": string;

    /** Creates a new UpdateResponse instance. */
    constructor($$source: Partial<UpdateResponse> = {}) {
        if (!("latest_version" in $$source)) {
            this["latest_version"] = "";
        }
        if (!("release_notes" in $$source)) {
            this["release_notes"] = "";
        }
        if (!("can_self_update" in $$source)) {
            this["can_self_update"] = false;
        }
        if (!("install_type" in $$source)) {
            this["install_type"] = "";
        }
        if (!("update_command" in $$source)) {
            this["update_command"] = "";
        }
        if (!("instructions" in $$source)) {
            this["instructions"] = "";
        }
        if (!("releases_url" in $$source)) {
            this["releases_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateResponse($$parsedSource as Partial<UpdateResponse>);
    }
}
