// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * UpdateResponse is what the frontend receives from a manual / periodic
 * update check. CanUpdate is false when the install cannot self-update
 * (e.g. AppImage, deb/rpm installs) or the license does not cover the
 * new version - in those cases NotificationUrl points the user at the
 * right place instead.
 */
export class UpdateResponse {
    "latest_version": string;
    "can_update": boolean;
    "release_notes": string;
    "notification_text": string;
    "notification_url": string;

    /** Creates a new UpdateResponse instance. */
    constructor($$source: Partial<UpdateResponse> = {}) {
        if (!("latest_version" in $$source)) {
            this["latest_version"] = "";
        }
        if (!("can_update" in $$source)) {
            this["can_update"] = false;
        }
        if (!("release_notes" in $$source)) {
            this["release_notes"] = "";
        }
        if (!("notification_text" in $$source)) {
            this["notification_text"] = "";
        }
        if (!("notification_url" in $$source)) {
            this["notification_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateResponse($$parsedSource as Partial<UpdateResponse>);
    }
}
