// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSubscription(arg1) {
  return window['go']['app']['App']['AddSubscription'](arg1);
}

export function CheckForUpdates() {
  return window['go']['app']['App']['CheckForUpdates']();
}

export function ChooseCertFile(arg1) {
  return window['go']['app']['App']['ChooseCertFile'](arg1);
}

export function ChooseDirectory(arg1) {
  return window['go']['app']['App']['ChooseDirectory'](arg1);
}

export function ClearConnectionHistory(arg1) {
  return window['go']['app']['App']['ClearConnectionHistory'](arg1);
}

export function ConnectMqtt(arg1) {
  return window['go']['app']['App']['ConnectMqtt'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['app']['App']['DeleteConnection'](arg1);
}

export function DeleteFilterHistoryEntry(arg1, arg2) {
  return window['go']['app']['App']['DeleteFilterHistoryEntry'](arg1, arg2);
}

export function DeletePublishHistoryEntry(arg1) {
  return window['go']['app']['App']['DeletePublishHistoryEntry'](arg1);
}

export function DeleteRetainedMessage(arg1, arg2) {
  return window['go']['app']['App']['DeleteRetainedMessage'](arg1, arg2);
}

export function DeleteSubscription(arg1, arg2) {
  return window['go']['app']['App']['DeleteSubscription'](arg1, arg2);
}

export function DisconnectMqtt(arg1) {
  return window['go']['app']['App']['DisconnectMqtt'](arg1);
}

export function GetAllConnections() {
  return window['go']['app']['App']['GetAllConnections']();
}

export function GetAllSubscriptionsByConnectionId() {
  return window['go']['app']['App']['GetAllSubscriptionsByConnectionId']();
}

export function GetEnvInfo() {
  return window['go']['app']['App']['GetEnvInfo']();
}

export function GetFilterHistoriesForConnection(arg1) {
  return window['go']['app']['App']['GetFilterHistoriesForConnection'](arg1);
}

export function GetMatchingProtoDescriptorForTopic(arg1, arg2) {
  return window['go']['app']['App']['GetMatchingProtoDescriptorForTopic'](arg1, arg2);
}

export function GetMatchingSubscriptionForTopic(arg1, arg2) {
  return window['go']['app']['App']['GetMatchingSubscriptionForTopic'](arg1, arg2);
}

export function GetMessageHistory(arg1, arg2) {
  return window['go']['app']['App']['GetMessageHistory'](arg1, arg2);
}

export function GetMqttStats() {
  return window['go']['app']['App']['GetMqttStats']();
}

export function GetPanelSizes() {
  return window['go']['app']['App']['GetPanelSizes']();
}

export function GetPublishHistoriesForConnection(arg1) {
  return window['go']['app']['App']['GetPublishHistoriesForConnection'](arg1);
}

export function GetSortStates() {
  return window['go']['app']['App']['GetSortStates']();
}

export function LoadOpenTabs() {
  return window['go']['app']['App']['LoadOpenTabs']();
}

export function LoadProtoRegistry(arg1) {
  return window['go']['app']['App']['LoadProtoRegistry'](arg1);
}

export function NewConnection() {
  return window['go']['app']['App']['NewConnection']();
}

export function PublishMqtt(arg1, arg2) {
  return window['go']['app']['App']['PublishMqtt'](arg1, arg2);
}

export function SaveFilterHistoryEntry(arg1, arg2) {
  return window['go']['app']['App']['SaveFilterHistoryEntry'](arg1, arg2);
}

export function SavePublishHistoryEntry(arg1) {
  return window['go']['app']['App']['SavePublishHistoryEntry'](arg1);
}

export function StartUpdate() {
  return window['go']['app']['App']['StartUpdate']();
}

export function Startup(arg1, arg2) {
  return window['go']['app']['App']['Startup'](arg1, arg2);
}

export function UpdateConnection(arg1) {
  return window['go']['app']['App']['UpdateConnection'](arg1);
}

export function UpdateOpenConnectionTabs(arg1) {
  return window['go']['app']['App']['UpdateOpenConnectionTabs'](arg1);
}

export function UpdatePanelSize(arg1, arg2, arg3) {
  return window['go']['app']['App']['UpdatePanelSize'](arg1, arg2, arg3);
}

export function UpdateSortState(arg1, arg2, arg3) {
  return window['go']['app']['App']['UpdateSortState'](arg1, arg2, arg3);
}

export function UpdateSubscription(arg1, arg2) {
  return window['go']['app']['App']['UpdateSubscription'](arg1, arg2);
}
