// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetConnectionEventsSet(connectionId: number): $CancellablePromise<$models.ConnectionEventsSet> {
    return $Call.ByID(278216920, connectionId).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GlobalEventNames returns all global event names. It exists so the
 * GlobalEvent enum is included in the generated frontend bindings.
 */
export function GlobalEventNames(): $CancellablePromise<$models.GlobalEvent[]> {
    return $Call.ByID(2419412048).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ConnectionEventsSet.createFrom;
const $$createType1 = $Create.Array($Create.Any);
