// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetConnectionEventsSet(connectionId: number): Promise<$models.ConnectionEventsSet> & { cancel(): void } {
    let $resultPromise = $Call.ByID(278216920, connectionId) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType0($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GlobalEventNames returns all global event names. It exists so the
 * GlobalEvent enum is included in the generated frontend bindings.
 */
export function GlobalEventNames(): Promise<$models.GlobalEvent[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2419412048) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

// Private type creation functions
const $$createType0 = $models.ConnectionEventsSet.createFrom;
const $$createType1 = $Create.Array($Create.Any);
