// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class ConnectionEventsSet {
    "mqttConnected": string;
    "mqttDisconnected": string;
    "mqttConnecting": string;
    "mqttReconnecting": string;
    "mqttClientError": string;
    "mqttMessages": string;
    "mqttLatency": string;
    "mqttClearHistory": string;

    /** Creates a new ConnectionEventsSet instance. */
    constructor($$source: Partial<ConnectionEventsSet> = {}) {
        if (!("mqttConnected" in $$source)) {
            this["mqttConnected"] = "";
        }
        if (!("mqttDisconnected" in $$source)) {
            this["mqttDisconnected"] = "";
        }
        if (!("mqttConnecting" in $$source)) {
            this["mqttConnecting"] = "";
        }
        if (!("mqttReconnecting" in $$source)) {
            this["mqttReconnecting"] = "";
        }
        if (!("mqttClientError" in $$source)) {
            this["mqttClientError"] = "";
        }
        if (!("mqttMessages" in $$source)) {
            this["mqttMessages"] = "";
        }
        if (!("mqttLatency" in $$source)) {
            this["mqttLatency"] = "";
        }
        if (!("mqttClearHistory" in $$source)) {
            this["mqttClearHistory"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionEventsSet instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectionEventsSet {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionEventsSet($$parsedSource as Partial<ConnectionEventsSet>);
    }
}

export enum GlobalEvent {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ConnectionDeleted = "ConnectionDeleted",
    UpdateAvailable = "UpdateAvailable",
};
