import {
  House,
  Clock,
  Heart,
  Plus,
  PlusSquare,
  Copy,
  ArrowsOutSimple,
  ArrowsInSimple,
  X,
  XCircle,
  Bell,
  Gear,
  MagnifyingGlass,
  CaretDown,
  CaretUp,
  Check,
  CheckSquare,
  Files,
  File,
  FileArrowDown,
  ArrowsClockwise,
  Folder,
  FolderOpen,
  ArrowElbowDownRight,
  PlugsConnected,
  Plugs,
  Play,
  ArrowLineLeft,
  Warning,
  CaretLeft,
  CaretRight,
  ArrowsSplit,
  EnvelopeSimple,
  Trash,
  Square,
  DotsThreeOutlineVertical,
  Confetti,
  Bug,
  DownloadSimple,
  PencilSimple,
  ClockCounterClockwise,
  Info,
  Sun,
  Moon,
  SidebarSimple,
  DotsThree,
  ArrowLeft,
  PlusCircle,
  ChartLine,
  Eye,
  EyeSlash,
  ArrowSquareOut,
  Pause,
  Image,
  SquareSplitHorizontal,
  SquareSplitVertical,
} from "phosphor-svelte";

export const ICON_MAP = {
  // General
  notification: Bell,
  clock: Clock,
  heart: Heart,
  home: House,
  options: Gear,
  settings: Gear,
  files: Files,
  file: File,
  fileOpen: FileArrowDown,
  folder: Folder,
  folderOpen: FolderOpen,
  subItem: ArrowElbowDownRight,
  children: ArrowsSplit,
  warning: Warning,
  message: EnvelopeSimple,
  menu: DotsThreeOutlineVertical,
  menuDots: DotsThree,
  info: Info,
  lightMode: Sun,
  darkMode: Moon,

  // Actions
  close: X,
  closeCircle: XCircle,
  collapse: ArrowsInSimple,
  edit: PencilSimple,
  shiftPanelLeft: ArrowLineLeft,
  copy: Copy,
  down: CaretDown,
  up: CaretUp,
  left: CaretLeft,
  right: CaretRight,
  expand: ArrowsOutSimple,
  plus: Plus,
  plusSquare: PlusSquare,
  plusCircle: PlusCircle,
  back: ArrowLeft,
  sidebar: SidebarSimple,
  search: MagnifyingGlass,
  refresh: ArrowsClockwise,
  connect: Play,
  disconnect: Plugs,
  delete: Trash,
  feature: Confetti,
  bug: Bug,
  download: DownloadSimple,
  chart: ChartLine,
  show: Eye,
  hide: EyeSlash,
  popOut: ArrowSquareOut,
  pause: Pause,
  image: Image,
  dockRight: SquareSplitHorizontal,
  dockBottom: SquareSplitVertical,

  // States
  lastConnected: ClockCounterClockwise,
  history: ClockCounterClockwise,
  tick: Check,
  tickSquare: CheckSquare,
  unticked: Square,
  ticked: CheckSquare,
  connected: PlugsConnected,
  disconnected: Plugs,
};

export type IconType = keyof typeof ICON_MAP;
