// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ConnectionStats is the snapshot handed to the frontend by GetStats. It is a
 * plain value type so the counters can never be read while a message is
 * updating them.
 */
export class ConnectionStats {
    "messagesReceived": number;
    "messagesSent": number;
    "bytesReceived": number;
    "bytesSent": number;

    /** Creates a new ConnectionStats instance. */
    constructor($$source: Partial<ConnectionStats> = {}) {
        if (!("messagesReceived" in $$source)) {
            this["messagesReceived"] = 0;
        }
        if (!("messagesSent" in $$source)) {
            this["messagesSent"] = 0;
        }
        if (!("bytesReceived" in $$source)) {
            this["bytesReceived"] = 0;
        }
        if (!("bytesSent" in $$source)) {
            this["bytesSent"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionStats instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectionStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionStats($$parsedSource as Partial<ConnectionStats>);
    }
}

/**
 * LogEntry is one client-log line, surfaced to the frontend as-is.
 */
export class LogEntry {
    "timestampMs": number;
    "level": string;
    "message": string;

    /** Creates a new LogEntry instance. */
    constructor($$source: Partial<LogEntry> = {}) {
        if (!("timestampMs" in $$source)) {
            this["timestampMs"] = 0;
        }
        if (!("level" in $$source)) {
            this["level"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): LogEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogEntry($$parsedSource as Partial<LogEntry>);
    }
}

export class MessageProperties {
    "correlationData": string;
    "contentType": string;
    "responseTopic": string;
    "payloadFormat": number | null;
    "messageExpiry": number | null;
    "subscriptionIdentifier": number | null;
    "topicAlias": number | null;
    "userProperties": { [_ in string]?: string };

    /** Creates a new MessageProperties instance. */
    constructor($$source: Partial<MessageProperties> = {}) {
        if (!("correlationData" in $$source)) {
            this["correlationData"] = "";
        }
        if (!("contentType" in $$source)) {
            this["contentType"] = "";
        }
        if (!("responseTopic" in $$source)) {
            this["responseTopic"] = "";
        }
        if (!("payloadFormat" in $$source)) {
            this["payloadFormat"] = null;
        }
        if (!("messageExpiry" in $$source)) {
            this["messageExpiry"] = null;
        }
        if (!("subscriptionIdentifier" in $$source)) {
            this["subscriptionIdentifier"] = null;
        }
        if (!("topicAlias" in $$source)) {
            this["topicAlias"] = null;
        }
        if (!("userProperties" in $$source)) {
            this["userProperties"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageProperties instance from a string or object.
     */
    static createFrom($$source: any = {}): MessageProperties {
        const $$createField0_0 = $Create.ByteSlice;
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("correlationData" in $$parsedSource) {
            $$parsedSource["correlationData"] = $$createField0_0($$parsedSource["correlationData"]);
        }
        if ("userProperties" in $$parsedSource) {
            $$parsedSource["userProperties"] = $$createField7_0($$parsedSource["userProperties"]);
        }
        return new MessageProperties($$parsedSource as Partial<MessageProperties>);
    }
}

export class MqttMessage {
    "id": string;
    "topic": string;
    "payload": string;
    "qos": number;
    "retain": boolean;
    "properties"?: MessageProperties | null;
    "timeMs": number;
    "middlewareProperties"?: { [_ in string]?: any } | null;
    "Time": string;

    /** Creates a new MqttMessage instance. */
    constructor($$source: Partial<MqttMessage> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("payload" in $$source)) {
            this["payload"] = "";
        }
        if (!("qos" in $$source)) {
            this["qos"] = 0;
        }
        if (!("retain" in $$source)) {
            this["retain"] = false;
        }
        if (!("timeMs" in $$source)) {
            this["timeMs"] = 0;
        }
        if (!("Time" in $$source)) {
            this["Time"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MqttMessage instance from a string or object.
     */
    static createFrom($$source: any = {}): MqttMessage {
        const $$createField2_0 = $Create.ByteSlice;
        const $$createField5_0 = $$createType2;
        const $$createField7_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("payload" in $$parsedSource) {
            $$parsedSource["payload"] = $$createField2_0($$parsedSource["payload"]);
        }
        if ("properties" in $$parsedSource) {
            $$parsedSource["properties"] = $$createField5_0($$parsedSource["properties"]);
        }
        if ("middlewareProperties" in $$parsedSource) {
            $$parsedSource["middlewareProperties"] = $$createField7_0($$parsedSource["middlewareProperties"]);
        }
        return new MqttMessage($$parsedSource as Partial<MqttMessage>);
    }
}

/**
 * MqttMessageStub is the lightweight projection of MqttMessage used to
 * populate the selection timeline: everything the timeline needs to render a
 * dot (id, arrival time, qos/retain flags) but never the payload. Selecting a
 * busy topic (potentially 150k+ stored messages) fetches a bounded window of
 * these instead of full messages, so the bridge never has to serialize tens
 * of MB of payload just to draw dots on a timeline. Payloads are fetched
 * individually, on demand, via GetMessageById/GetMessageTimeline callers.
 */
export class MqttMessageStub {
    "id": string;
    "timeMs": number;
    "qos": number;
    "retain": boolean;

    /** Creates a new MqttMessageStub instance. */
    constructor($$source: Partial<MqttMessageStub> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("timeMs" in $$source)) {
            this["timeMs"] = 0;
        }
        if (!("qos" in $$source)) {
            this["qos"] = 0;
        }
        if (!("retain" in $$source)) {
            this["retain"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MqttMessageStub instance from a string or object.
     */
    static createFrom($$source: any = {}): MqttMessageStub {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MqttMessageStub($$parsedSource as Partial<MqttMessageStub>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = MessageProperties.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = $Create.Nullable($$createType3);
