name: Release MQTT Viewer - Mac

on:
  release:
    types: [published]

jobs:
  release:
    strategy:
      matrix:
        build:
          - platform: darwin/amd64
            arch: amd64
            os: macos-latest
            tag: darwin_amd64
          - platform: darwin/arm64
            arch: arm64
            os: macos-latest
            tag: darwin_arm64
    runs-on: ${{ matrix.build.os }}
    name: Release MQTT Viewer (${{ matrix.build.tag }})
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      # Set up common, sanitised environment variables

      - name: Normalise version tag
        id: normalise_version
        shell: bash
        run: |
          if [ -n "${{ github.event.release.tag_name }}" ]; then
            version=$(echo ${{ github.event.release.tag_name }})
          else
            version="v0.0.0"
          fi
          bundle_version="${version#v}"
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "bundle_version=$bundle_version" >> $GITHUB_OUTPUT

      - name: Define output filename
        id: define_filename
        shell: bash
        run: |
          echo "filename=MQTT_Viewer_${{ steps.normalise_version.outputs.version }}_${{ matrix.build.tag }}" >> $GITHUB_OUTPUT

      # Set up development dependencies

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.0"

      - name: Install Wails v3
        shell: bash
        run: go install github.com/wailsapp/wails/v3/cmd/wails3@v3.0.0-alpha.84

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.15.0"

      - name: Install pnpm
        shell: bash
        run: npm install -g pnpm

      - name: Import code signing certificate from Github Secrets
        uses: Apple-Actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_P12_BASE64 }}
          p12-password: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_PASSWORD }}

      - name: Use mac app icon
        shell: bash
        run: |
          cd build
          rm -f appicon.png
          mv appicon-mac.png appicon.png

      # Build

      - name: Store notarization credentials
        shell: bash
        run: |
          wails3 signing credentials \
            --apple-id "${{ secrets.AC_USERNAME }}" \
            --team-id "${{ secrets.AC_PROVIDER }}" \
            --password "${{ secrets.AC_PASSWORD }}" \
            --profile "mqtt-viewer-notarize"

      - name: Build, sign, and notarize macOS app
        shell: bash
        run: |
          echo "building app on ${{ matrix.build.platform }}"
          LD_FLAGS="-X mqtt-viewer/backend/env.Version=${{ steps.normalise_version.outputs.version }}"
          LD_FLAGS="${LD_FLAGS} -X mqtt-viewer/backend/env.MachineIdProtectString=${{ secrets.MACHINE_ID_SECRET }}"
          LD_FLAGS="${LD_FLAGS} -X mqtt-viewer/backend/env.CloudUsername=${{ secrets.CLOUD_USERNAME }}"
          LD_FLAGS="${LD_FLAGS} -X mqtt-viewer/backend/env.CloudPassword=${{ secrets.CLOUD_PASSWORD }}"
          wails3 task darwin:sign:notarize \
            ARCH=${{ matrix.build.arch }} \
            VERSION=${{ steps.normalise_version.outputs.version }} \
            BUNDLE_VERSION=${{ steps.normalise_version.outputs.bundle_version }} \
            LD_FLAGS="${LD_FLAGS}" \
            SIGN_IDENTITY="Samuel Webster" \
            KEYCHAIN_PROFILE="mqtt-viewer-notarize"
          echo "Zipping Package"
          ditto -c -k --keepParent "./bin/MQTTViewer.app" ./bin/MQTTViewer.zip

      # Publish

      - name: Rename release zip
        shell: bash
        run: mv bin/MQTTViewer.zip bin/${{ steps.define_filename.outputs.filename }}.zip

      - name: Upload release zip
        uses: alexellis/upload-assets@0.4.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["bin/${{ steps.define_filename.outputs.filename }}.zip"]'
